export const box: string;
export const description: string;
export const title: string;
export const button: string;
export const info: string;
export const main: string;
export const comments: string;
export const upperBox: string;
export const upperTitle: string;
